feat: customizable alphabet using OcrEngineParams
robertknight/ocrs pull request #100
Opened 2024-08-22 16:22 UTC by Phaired

I made this I don't now if it's good enough to be merged, it just add a parameter with the same default value as before.

2024-08-26 09:14 UTC, robertknight requested changes
Hello. Thanks for this. The API looks good. Some comments and whitespace went missing in this diff, can you reinstate them. Also there are a few comments that can be omitted because the code is clear enough on its own.

2024-08-26 10:47 UTC, Phaired commented
I made modifications based on your comment. Please let me know if it's good for you

2024-08-30 17:47 UTC, robertknight commented
Sorry for the delay. The changes look good. I'll get them merged soon.

2024-08-30 19:22 UTC, robertknight approved these changes

2024-08-30 19:22 UTC, merged